# -*- coding: utf-8 -*-
"""ARMSTRONG NUMBER

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IRCEhunTp2lcsfLDdXrXC45KM4cAYdHM

**COVID-19 RISK WITH IF STATEMENT**
"""

while True:
  number = input("Please enter a positive integer number: ")
  sum_num = 0

  if not number.isdigit():    
    print(number, "is invalid.Please enter valid input")

  elif int(number) >= 0 : 
    for i in range(len(number)): 
      sum_num = sum_num + int(number[i]) ** len(number)

    if sum_num == int(number):   
      print(number, "is an Armstrong Number")
      break
    else: 
      print(number, "is NOT an Armstrong Number")     
      break